describe('template spec', () => {
  it('passes', () => {
    cy.visit('/')
    cy.intercept("**/api/programs").as("api")
    cy.wait("@api")
    cy.contains('h1', 'Find Local Programs Near You')
    cy.get('[data-cy="zip-input"]').type('19801')
    cy.get('[data-cy="search-button"]').click()
    cy.get('[data-cy="keyword-input"]')
    cy.get('.filter-toggle').click()
    cy.get('.filters-header').should('exist')
    cy.get('.clear-recent').click()
    cy.get('.recent-searches-list').should('not.exist')
  })
})