CREATE TABLE IF NOT EXISTS programs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    zip_code VARCHAR(5) NOT NULL,
    organization VARCHAR(255) NOT NULL,
    services TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    ages VARCHAR(50) NOT NULL,
    location VARCHAR(255),
    contact_website VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(20),
    description TEXT,
    hours VARCHAR(255),
    cost VARCHAR(255),
    registration_info TEXT
);

INSERT INTO programs (zip_code, organization, services, type, ages, location, contact_website, contact_email, contact_phone, description, hours, cost, registration_info) VALUES
('19801', 'Walnut Street YMCA', 'Offers preschool, school-age childcare, youth development, teen leadership programs, summer day camps, swim lessons, and lifeguard training.', 'Sports, education, lifeguard', '2mos - 17yrs', '1000 N Walnut St, Wilmington, DE 19801', 'https://www.ymcade.org/walnut-street-ymca', 'info@ymcade.org', '(302) 571-6975', 'A full-service YMCA offering a wide range of programs for youth development, including sports, education, and aquatic activities.', 'Mon-Fri: 5:30am-9pm, Sat: 7am-5pm, Sun: 8am-4pm', 'Membership required, varies by program', 'Registration available online or in person'),
('19801', 'Central YMCA', 'Provides preschool programs and childcare services.', 'Preschool, Childcare', '2mos - 5yrs', '11th and Market Sts, Wilmington, DE 19801', 'https://www.ymcade.org/central-ymca', 'central@ymcade.org', '(302) 571-6975', 'Downtown YMCA focused on early childhood education and development.', 'Mon-Fri: 6am-8pm, Sat: 7am-5pm, Sun: 8am-4pm', 'Membership required, financial assistance available', 'Registration required, contact for availability'),
('19801', 'Wilmington Youth Rowing Association (WYRA)', 'Inclusive rowing programs for youth of all abilities and backgrounds.', 'Rowing Programs/Sports', '11 - 18yrs', '1000 N Walnut St, Wilmington, DE 19801', 'https://www.wyra.org', 'info@wyra.org', '(302) 555-0123', 'Premier rowing program offering competitive and recreational opportunities for youth.', 'Practice times vary by season', 'Seasonal fees apply, equipment provided', 'Tryouts required, contact for schedule'),
('19801', 'Youth Public Safety Academy', 'A two-week program introducing youth to public safety careers and training.', 'Career training, education', '13 - 17yrs', '300 N Walnut St, Wilmington, DE 19801', 'https://www.wilmingtonde.gov/ypsa', 'ypsa@wilmingtonde.gov', '(302) 576-2171', 'Intensive program exposing youth to careers in law enforcement, fire service, and emergency medical services.', 'Summer program, 9am-3pm', 'Free program', 'Application required, limited spots available'),
('19801', 'Serviam Girls Academy', 'Tuition-free education for girls in grades 5–8, focusing on academic excellence and leadership.', 'Education, Leadership', '10 - 14yrs', '1801 W 6th St, Wilmington, DE 19801', 'https://www.serviamgirlsacademy.org', 'info@serviamgirlsacademy.org', '(302) 762-5822', 'Private Catholic school providing quality education and leadership development for girls.', 'School hours: 8am-3pm', 'Tuition-free, donations accepted', 'Application and interview required'),
('19801', 'Mary Campbell Center', 'Children and Youth Program: Offers unique activities for children with special needs and their families.', 'Special Needs, activities', '3 - 21yrs', '4641 Weldin Rd, Wilmington, DE 19801', 'https://www.marycampbellcenter.org', 'info@marycampbellcenter.org', '(302) 999-0731', 'Specialized programs for children and youth with disabilities.', 'Program hours vary', 'Sliding scale fees available', 'Assessment required, contact for details'),
('19802', 'UrbanPromise Wilmington', 'Provides after-school programs, summer camps, and leadership training for youth.', 'Education, After-School Programs, Summer Camp, Leadership Training', '14-18yrs', '1100 N Market St, Wilmington, DE 19802', 'https://www.urbanpromisewilmington.org', 'info@urbanpromisewilmington.org', '(302) 425-5503', 'Comprehensive youth development program focusing on education and leadership.', 'After-school: 3pm-6pm, Summer: 9am-4pm', 'Free program', 'Registration required, limited spots'),
('19802', 'Police Athletic League of Wilmington (PALW)', 'Offers before and after care programs, summer camps, and educational activities.', 'Before After Care, Summer Camp, Educational, Activities', '8 - 18yrs', '3707 N Market St, Wilmington, DE 19802', 'https://www.palw.org', 'info@palw.org', '(302) 576-3633', 'Youth development program combining sports, education, and community engagement.', 'Before care: 7am-9am, After care: 3pm-6pm', 'Sliding scale fees', 'Registration required'),
('19802', 'Kingswood Community Center', 'Features early learning programs, after-school activities, and teen engagement initiatives.', 'Education, activities', '1 - 5yrs, 5 - 18yrs', '2300 Bowers St, Wilmington, DE 19802', 'https://www.kingswoodcc.org', 'info@kingswoodcc.org', '(302) 658-4171', 'Community center offering diverse programs for all ages.', 'Mon-Fri: 9am-8pm, Sat: 10am-4pm', 'Membership fees apply', 'Walk-in registration available'),
('19802', 'The Warehouse', 'A teen-designed community center offering programs for ages 13–19, including leadership and educational support.', 'Teen Programs, Leadership, Educational Support', '13 - 19yrs', '800 N Market St, Wilmington, DE 19802', 'https://www.warehousewilmington.org', 'info@warehousewilmington.org', '(302) 425-4640', 'Youth-led community center providing safe space and programs for teens.', 'Mon-Fri: 3pm-8pm, Sat: 12pm-6pm', 'Free program', 'Open to all teens'),
('19802', 'i9 Sports at Wilmington-Pilot School', 'Provides youth sports leagues, camps, and clinics focusing on fun and skill development.', 'Sports - Basketball, Flag football, soccer, baseball', '3 - 17yrs', '1000 N Union St, Wilmington, DE 19802', 'https://www.i9sports.com', 'wilmington@i9sports.com', '(302) 555-0124', 'Organized sports programs emphasizing fun, safety, and skill development.', 'Weekday evenings and weekends', 'Seasonal registration fees', 'Online registration available'),
('19802', 'Haynes Park – Summer Food Service Program', 'Offers free breakfast and lunch during summer months to youth in the community.', 'Summer Food Service', '1 - 18yrs', 'Haynes Park, Wilmington, DE 19802', 'https://www.wilmingtonde.gov/parks', 'parks@wilmingtonde.gov', '(302) 576-3870', 'Free summer meal program for youth in the community.', 'Breakfast: 8am-9am, Lunch: 12pm-1pm', 'Free program', 'No registration required'),
('19803', 'Brandywine YMCA', 'Offers youth sports, enrichment workshops, swim lessons, summer camps, and small group training.', 'Youth Sports, Workshops, Swim Lessons, Summer Camps, Training', '1 - 24yrs', '3 Mount Lebanon Rd, Wilmington, DE 19803', 'https://www.ymcade.org/brandywine-ymca', 'brandywine@ymcade.org', '(302) 478-9622', 'Full-service YMCA with extensive youth programs and facilities.', 'Mon-Fri: 5:30am-9pm, Sat: 7am-5pm, Sun: 8am-4pm', 'Membership required, varies by program', 'Registration available online or in person'),
('19803', 'Siegel JCC', 'Provides early childhood education, youth and teen programs, summer camps, and recreational facilities.', 'Early Childhood Education, Youth Programs, Summer Camps, Recreation', '2mos - 17yrs', '101 Garden of Eden Rd, Wilmington, DE 19803', 'https://www.siegeljcc.org', 'info@siegeljcc.org', '(302) 478-5660', 'Jewish Community Center offering diverse programs for all ages.', 'Mon-Fri: 6am-9pm, Sat-Sun: 8am-5pm', 'Membership required, financial assistance available', 'Registration required'),
('19805', 'West End Neighborhood House', 'Offers youth development programs focusing on education, recreation, and life skills for ages 5–18.', 'Youth Development, Education, Recreation, Life Skills', '5 - 18yrs', '710 N Lincoln St, Wilmington, DE 19805', 'https://www.westendnh.org', 'info@westendnh.org', '(302) 658-4171', 'Comprehensive youth development center serving the West End community.', 'Mon-Fri: 9am-8pm, Sat: 10am-4pm', 'Sliding scale fees available', 'Registration required'),
('19805', 'Out of School Youth Program – West End Neighborhood House', 'An 8-week program integrating employability skills training to prepare youth for the workforce.', 'Employability Skills Training', '16 - 23yrs', '710 N Lincoln St, Wilmington, DE 19805', 'https://www.westendnh.org/youth', 'youth@westendnh.org', '(302) 658-4171', 'Workforce development program for out-of-school youth.', 'Mon-Fri: 9am-4pm', 'Free program', 'Application and interview required'),
('19805', 'William "Hicks" Anderson Community Center', 'Provides organized sports leagues, youth camps, field trips, tutoring, and various recreational activities.', 'Sports Leagues, Youth Camps, Field Trips, Tutoring, Recreation', '6 - 17yrs', '501 N Madison St, Wilmington, DE 19805', 'https://www.hicksandersoncenter.org', 'info@hicksandersoncenter.org', '(302) 658-4171', 'Community center offering diverse programs for youth development.', 'Mon-Fri: 9am-8pm, Sat: 10am-4pm', 'Program fees vary', 'Registration required'),
('19806', 'Delaware Center for Horticulture', 'Offers youth programs focusing on horticulture education and employment training.', 'Horticulture Education, Employment Training', '3 - 18yrs', '1810 N Dupont St, Wilmington, DE 19806', 'https://www.thedch.org', 'info@thedch.org', '(302) 658-6262', 'Educational programs connecting youth with nature and horticulture.', 'Program hours vary', 'Program fees vary', 'Registration required'),
('19806', 'Volunteer Opportunities at St. Stephen''s', 'Engages youth in community service through Delaware''s highest-volume pantry, serving over 1,300 families monthly.', 'Community Service', '14 - 18yrs', '1301 N Broom St, Wilmington, DE 19806', 'https://www.ststephensde.org', 'volunteer@ststephensde.org', '(302) 656-5448', 'Community service opportunities for youth at a local food pantry.', 'Mon-Fri: 9am-4pm', 'Free program', 'Orientation required');

